### ISSUE TITLE
movies found, but series not

### ISSUE THREAD

**Issue by Yapping7409** [Gabisonfire/knightcrawler#140]
**Describe the bug**
Movies are found, but series are not found even thought they are in the database.

**To Reproduce**
Installed via docker locally and using npm for https.

**Expected behavior**
I expected to also see results for series, but they are not found.

**Hardware:**
 - OS and distro: Ubuntu 22.04

**Comment by iPromKnight** [comment]
This has been fixed in #145
I'll include a small sql script soon that you can use to re-ingest all your series data thats at fault

Thanks for reporting.

**Comment by iPromKnight** [comment]
```sql
BEGIN;

DROP TABLE IF EXISTS temp_info_hashes;

CREATE TEMPORARY TABLE temp_info_hashes AS
SELECT "infoHash" FROM files
WHERE ("imdbSeason" IS NULL or "imdbSeason" = 0)
  AND ("imdbEpisode" IS NULL or "imdbEpisode" = 0)
  AND ("kitsuEpisode" IS NULL or "kitsuEpisode" = 0);

DELETE FROM torrents
WHERE "infoHash" IN (SELECT "infoHash" FROM temp_info_hashes)
AND (LOWER("type") != 'movie' AND LOWER("type") != 'movies');

UPDATE ingested_torrents
SET processed = false
WHERE "category" = 'tv'
  AND info_hash IN (SELECT "infoHash" FROM temp_info_hashes);

DROP TABLE temp_info_hashes;

COMMIT;
```

This will remove all the broken series torrents, which the producer will then auto pickup again and re-add to the queue for processing

**Comment by Yapping7409** [comment]
Thanks for all the work you did! I completely reset the containers since i didn't have a huge number of torrents yet, but i am still having some problems. Some series are found in stremio while others are not. Should all the category tv ingested torrents work when they are in the database or does imdb metadata update when available?
